spring:
  datasource:
    url: jdbc:mysql://localhost:3306/searchvidsdevdb?useSSL=false&serverTimezone=UTC
    username: root
    password: rootpassword
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

jwt:
  jwtSecret: clientDevSecret
  jwtExpiration: 86400